### ISSUE TITLE
Does this parse Instrument procedures too?

### ISSUE THREAD

**Issue by idouiri9806** [misterrodg/cifparse#1]
Hi! nice project, I was wondering if it does parse instrument approaches like SID, STAR etc? I am unsure where exactly to get that data from prolly CIFP ?

**Comment by misterrodg** [comment]
Hi! Thanks! It parses everything that is in the FAA CIFP file: airports, airways, controlled airspace, heliports, localizer and glideslope locations/capabilities, NDBs, SID/STAR/IAPs, restrictive airspace (MOA/P/R/W airspace), runways, VORs and DMEs, and waypoints (terminal and enroute).

The `docs` directory explains what is available in each of those: https://github.com/misterrodg/cifparse/tree/main/docs

The CIFP is available here: https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/cifp/download/

I'm using `cifparse` in one of my other projects to parse the CIFP data into a database. I then use that data to create geojson charts.
You can see the cifparse lines here on lines 21 to 33: https://github.com/misterrodg/FacilityMapper/blob/main/main.py

**Comment by idouiri9806** [comment]
By GeoJSON charts, do you mean geo-referenced charts? aren't the FAA charts geo-referenced though ?I am also working on a hobby project to parse FAA data. Currently, I am using airspace data from OpenAIP. Just a question: is the data parsed from the airspace in GeoJSON format or something else?

**Comment by misterrodg** [comment]
Most of the FAA charts are geo-referenced now, yeah. This is more for using as a layer in an app like ForeFlight, or a mapping service like geojson.io. Either way, I just mentioned that as an example of how I was using the output from cifparse.

cifparse itself doesn't output anything by default. It's more of a library to be used in a Python project, but it can be set up to take the data, parse it, and dump it into a SQLite database. The README has an example at the very end where I use it to  dump the data into a database.

This is an example of the GeoJSON output so that I can visualize the GIBBZ5 into KIAD on a map, along with the fix names and altitudes/speeds without having to set something up to load a geo-referenced PDF:

![image](https://github.com/user-attachments/assets/5f6fa722-1b82-4a0d-8746-55c29fa51d40)
